### PR TITLE
fix(md-enhance): fix mathjax chtml output, close #2231

### LINKED ISSUE #2231: [Bug] Mathjax CHTML not working
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-plugin-md-enhance

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

CHTML output not working. This is because we can not get the style being injected properly.

### Additional context

Can use svg as a workaround

### PR DESCRIPTION
**Pull request by Mister-Hope**

### CODE REVIEW

**Comment by Mister-Hope** [comment]
@init-qy You may finish your work here after accpeting the invitation

**Comment by Mister-Hope** [comment]
Hi bro, you may be aware of https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/990bae6d43ed25b67686b4a331408bc92391cb5f, I reduce 260 packages in this commit.

**Comment by init-qy** [comment]
@Mister-Hope I have resolved conflicts by rebase on main, you can safely merge it.
I have tested these configs
```
      mathjax: {
        output: "chtml",
        chtml: {
          adaptiveCSS: false,
        } as MathjaxCommonHTMLOutputOptions,
      },

      mathjax: {
        output: "chtml",
      },

      mathjax: {
        output: "svg",
      },

      mathjax: true,
```

BTW, the full css is about 210kb with over 13,000 lines, you can add this into the doc.

the fonturl is still the cdn, is there any ways to package it into dist?

**Comment by Mister-Hope** [comment]
image

I will make some tweaks, and I would like to remind you about performance.

If you write code like this, it means that `getDocumentOptions` and `isImportGlobal` will be called with every math snippet, however user do not have local settings in pages or in math snippets, so the best way to do this is to create local variable before `md.use`. You'd better remind that while coding.

**Comment by init-qy** [comment]
> image
> 
> I will make some tweaks, and I would like to remind you about performance.
> 
> If you write code like this, it means that `getDocumentOptions` and `isImportGlobal` will be called with every math snippet, however user do not have local settings in pages or in math snippets, so the best way to do this is to create local variable before `md.use`. You'd better remind that while coding.

got it, will update later

**Comment by Mister-Hope** [comment]
Werid that the following is all not working, maybe we need to dig into source code to see how mathjax is handling it.

I made a full rebase of your code, to let `adaptiveCSS` work, the whole process shall share the same output processor, however your code is not doing that.

I add some unit test to ensure those works as a basic example output 500 lines while a full example with lots of syntax used outputs 1500 lines.

Also I try to rollup back svg to style injection on svg because svg do not support  `adaptiveCSS` when refactoring.

So now our main targets are:

1. Try to solve fontURL issue, locale resources should be the default behavior
2. Try to find out how many math blocks is the dividing line between outputing full style and binding style to svg tags.

**Comment by Mister-Hope** [comment]
Also I add a A11y option, but the test fails, maybe you can try helping with that? @init-qy

**Comment by init-qy** [comment]
> Also I try to rollup back svg to style injection on svg because svg do not support adaptiveCSS when refactoring.

svg also have global css style with output. without `adaptiveCSS`

It likes this, the css file is about 2kb, so still use inline css is not a good idea
```
mjx-container[jax="SVG"] {
  direction: ltr;
}

mjx-container[jax="SVG"] > svg {
  overflow: visible;
  min-height: 1px;
  min-width: 1px;
}
```

**Comment by init-qy** [comment]
> Try to solve fontURL issue, locale resources should be the default behavior
try to copy file from node_modules? or just copy the woff file to repo

mathjax publish a pre version 4, it has a extra package with font.
https://github.com/mathjax/MathJax-src/releases/tag/4.0.0-alpha.1
https://www.npmjs.com/package/mathjax-tex-font

**Comment by Mister-Hope** [comment]
Up to you. I must got Covid 19 yesterday and I am having a fever now. Your explanation sounds ok to me.

**Comment by init-qy** [comment]
You should go to rest right now !!!
I will take a look at a11y option, maybe tonight
later I'll commit a patch about svg style, with some explanations

**Comment by init-qy** [comment]
Since the whole process share the same output processor, the output css file is able to be used for the whole project(both svg and chtml), so we dont need matter the css file size, if set `adaptiveCSS=true`, the css file generated is always slimer than the full size.

Now, it will always generates a css file when mathjax is enabled.

The css file lines is related to the charactors which project use.

these words could add to tip:
```
Not recommended set `adaptiveCSS: false` when output is `chtml`, because it will generates a full size css file with over 200Kb.
```

At last, if this is accepeted, remove `juice`, I don't want to keep going back with `pnpm i`

**Comment by Mister-Hope** [comment]
I personally don't want to add tips, these should be advanced features and users should understand the consequences themselves, most people should only use output and a11y option I added in this pr.

**Comment by Mister-Hope** [comment]
Removing juice would be fine. BTW, I may rest in the comming days as my body temperature is  raising sharply, so I am expecting you to finish all the things if we want the pr to be meeged in recent

**Comment by init-qy** [comment]
> I personally don't want to add tips, these should be advanced features and users should understand the consequences themselves, most people should only use output and a11y option I added in this pr.

well, you're the boss

**Comment by init-qy** [comment]
Take a good rest, this pr is not very importent

**Comment by Mister-Hope** [comment]
> 

Actually, I am hearing a lot of users complaining we add too much contents in docs, so that they can not find a direct guideline easily. So I would prefer to keep "Advanced Option" appearing at "Cookbook", just like http://vuepress-theme-hope.github.io/v2/ and https://waline.js.org/

**Comment by Mister-Hope** [comment]
If the option handling of fontURL can not make us set somthing to work directly, maybe we can try convert the generated css to the correct path in `prepareMathjaxStyle` hook before `app.writeTemp` that should be easy. From the source code it seems can be a special replacement for `%%URL%%`

**Comment by init-qy** [comment]
GOOD NEWS!!
1. a11y has passed the test case.
2. fontURL is now use local resoures, I have test in both dev|prod and bunder. I use a special string `%%LOCAL%%` and replace it in `prepareMathjaxStyle`.

Next step is ensure currect works well in both bunder and dev|prod.
The fontURL is corrent with pnpm, Im not sure `npm` and `yarn` has the same url

**Comment by Mister-Hope** [comment]
Check my origin comment that you delete, you should use createRequire(import.meta.url).resolve('mathjax') to get mathjax location. That's the standard way.

**Comment by init-qy** [comment]
> Check my origin comment that you delete, you should use createRequire(import.meta.url).resolve('mathjax') to get mathjax location. That's the standard way.

Ok, I'll try it

**Comment by init-qy** [comment]
Since `createRequire(import.meta.url).resolve("mathjax-full")` output is `mathjax-full\components\src\node-main\node-main.js`
The other ways like `resolve("mathjax-full/es5/output/chtml/fonts/tex")`, add suffix to `mathjax-full`, fail
So I can only make this, a little strange, but did work.
```
          fontURL: resolve(
            createRequire(import.meta.url).resolve("mathjax-full"),
            "../../../../es5/output/chtml/fonts/woff-v2"
          ),
```

**Comment by Mister-Hope** [comment]
I make some tweaks because I don't like the following one. If you finished tesing

> fontURL: resolve(
>             createRequire(import.meta.url).resolve("mathjax-full"),
>             "../../../../es5/output/chtml/fonts/woff-v2"
>           ),


> Next step is ensure currect works well in both bunder and dev|prod.

 If you finished tesing, call me and I will make this be merged. Also if you have spare time you may help with #2339

**Comment by init-qy** [comment]
@Mister-Hope I have completed the test.

`../../client` confuse me, it works well on my computer but fails on action, is that because my os is `windows10`?
https://github.com/vuepress-theme-hope/vuepress-theme-hope/actions/runs/3763990154

**Comment by Mister-Hope** [comment]
You may place that variable in utils and export it

**Comment by init-qy** [comment]
> You may place that variable in utils and export it

yes, I make it

**Comment by Mister-Hope** [comment]
Hi, I migrate these code to https://github.com/Mister-Hope/mdit-plugins, shall I invite you to the new repo? Not sure if you have insterest making other markdown-it plugins, currently I am focusing adding some features related to obsidian grammar.

**Comment by init-qy** [comment]
Thank you very much for your invitation, I'm sorry for not replying in time as I'm also infected with covid-19.
I can try to make it in my free time, but I should not be as focused as you.
Perhaps you could tell me a little more about `some features related to obsidian grammar`

**Pull request merged**
