### PR TITLE
feat(theme): improve navbar alignment

### PR DESCRIPTION
**Pull request by yorunning**
调整`navbar`对齐方式，确保`navbar-center`位于页面正中心。

before
before
after
after

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Nice catch about the alignment, but I doubt this is a proper solution. Maybe you should try to edit the site title text length to see whether it still align well.

from your edits, you are making the center and right box becomes a horizontal flex one.

**Comment by yorunning** [comment]
> please provide a hidden site title screenshots

before:
before

after:
after

> and a pretty lone one. 

before:
before

after:
after

> Or you may reorganize the layout through options (e.g. reverse their sorting to see if it works well.)

尝试改变`navbarLayout`布局、删减项目、颠倒顺序显示都正常。但是标题过长并不能正真的居中。

**Comment by Mister-Hope** [comment]
Thanks for the detailed reply. Are the extra div really needed? I think it's possible to move styles into the original container.

So my concern is why is a extra div being added?

**Comment by Mister-Hope** [comment]
Thanks for contribution

**Pull request merged**
