### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by w473**

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Appreciated! Thanks for this.

Mean while could you try to resolve the conflicts? As I am moving 3 components back to theme in a recent commit.

**Comment by Mister-Hope** [comment]
Any update? Or shall I merge it manually?

**Comment by Mister-Hope** [comment]
I already updated to https://github.com/vuepress-theme-hope/vuepress-theme-hope/tree/pl-locale and sorry for the inconvinience.

You may pull that branch and commit to your repo then open a new PR.

I am already using your infomation with that commit. but to make yourself a contributor, the commit must be made by you to github.

**Comment by Mister-Hope** [comment]
You can open a new PR with that commit when you have time, I will releaase a new version once I merged it.

**Comment by w473** [comment]
Hi. Will do it next days. I just had 12 hours drive to my hometown for Easter :)

**Comment by Mister-Hope** [comment]
🙂

**Pull request closed without merging**
