### PR TITLE
Update replace.md

### PR DESCRIPTION
**Pull request by zuihou**
增加说明

### CODE REVIEW

**Review by Mister-Hope — CHANGES_REQUESTED** [review]
Could you update en docs as well? Also make sure you pass linter

**Comment by zuihou** [comment]
英文文档已更新

**Comment by Mister-Hope** [comment]
Pass linter plz?

**Comment by zuihou** [comment]
> Pass linter plz?

不会，要怎么弄？

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/fa8bbe5ac45c5122dae3c0d7569de7b99728cec9

**Pull request closed without merging**
