### PR TITLE
Update config.ts

### PR DESCRIPTION
**Pull request by ogpetya**
Russian and Ukrainian translations by Mery#5739

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Thanks for contributing this PR,but you make syntax in this commit so I cannot merge it directly.

If you don't mind, I will edit your commit and fix it and commit to v1 and V2 branch by myself with you as collaborator. Is that ok to you ?

**Comment by jamesbayly** [comment]
This would be very helpful

**Comment by Mister-Hope** [comment]
Hi, I still need your help.

Please edit i18n.ts in plugin folders as well to fully support those 2 languages.

- https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/v1/packages/comment/src/node/i18n.ts
- https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/v1/packages/components/src/node/i18n.ts
- https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/v1/packages/copy-code/src/node/i18n.ts
- https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/v1/packages/md-enhance/src/node/i18n.ts
- https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/v1/packages/photo-swipe/src/node/i18n.ts
- https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/v1/packages/pwa/src/node/i18n.ts
- https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/v1/packages/reading-time/src/node/i18n.ts

You help will be appreciated! 😉

**Comment by ogpetya** [comment]
approved

**Comment by Mister-Hope** [comment]
Any update about that request? The missing translation is stopping the project to run now. So I may revert that commit to make other changes and publish new versions if there is no activity for long time 😋

**Comment by ogpetya** [comment]
hey! I am on it! will finish it within 24 hours 😊

**Comment by ogpetya** [comment]
Hi, 
took a bit more than expected but I am ready 😊
All PR are created
Thanks!

**Comment by Mister-Hope** [comment]
> Hi, 
> 
> took a bit more than expected but I am ready 😊
> 
> All PR are created
> 
> Thanks!
> 
> 

Not sure if you saw my comment in another PR, you miss 2 translation in `comment` package.

**Comment by ogpetya** [comment]
@Mister-Hope updated in new PR https://github.com/vuepress-theme-hope/vuepress-theme-hope/pull/1180, thanks! ☺️

**Pull request merged**
