### PR TITLE
update: modified the code-demo style in md-enhance

### PR DESCRIPTION
**Pull request by coulsonzero**
Fixed some style problems, and provided a new custom style for code-demo.

### CODE REVIEW

**Comment by coulsonzero** [comment]
### Notice: the `custom` style  need to clear the comment to take effect !

### `base`

fixed the `copy-button` -`header:hover-border-radius` styles and so on

base

### `custom`

custom

**Comment by Mister-Hope** [comment]
image

This should be the actual before, I feel good about the redesigned copy code button

**Comment by Mister-Hope** [comment]
Any way, a new version is on its way to fix the broken code demo.

We add a variable called `--code-demo-header-bg-color` so you can change it to colors you like.

I prefer not to use dark colors in lightmode.

**Comment by Mister-Hope** [comment]
But I agree the button style can be improved. You may improve that under current bg color and PR welcome 🙂

**Comment by coulsonzero** [comment]
I mistakenly thought the copy button was a mistake, the `header:hover border-radius` maybe need to fixed, I also agree with you might prefer not to use dark colors in lightmode

**Comment by Mister-Hope** [comment]
Closing this one as we should get the fix.

**Comment by coulsonzero** [comment]
I noticed that the changes made have been very well，the problem has been solved, and I  also think we should close it

**Pull request closed without merging**
