### PR TITLE
feat: add Indonesian language support

### PR DESCRIPTION
**Pull request by agisnrynt**
I've added the Indonesian language, I hope that Indonesian language is implemented in the official theme you created

### CODE REVIEW

**Comment by Mister-Hope** [comment]
See https://github.com/vuepress-theme-hope/vuepress-theme-hope/pull/2255

Plug-in locales is used in theme too

**Comment by agisnrynt** [comment]
> See #2255
> 
> Plug-in locales is used in theme too

Can you show me the other files I need to change?

**Comment by agisnrynt** [comment]
> See #2255
> 
> Plug-in locales is used in theme too

I have revised and submitted, please review it.

**Comment by Mister-Hope** [comment]
Could you update docs as well

**Comment by agisnrynt** [comment]
> Could you update docs as well? This ensure other people know that Indonesian is supported

Of course, I will also update the docs for Indonesian, to see if my translation is correct and not weird

**Pull request merged**
