### PR TITLE
fix(auto-catalog): fix ol style

### PR DESCRIPTION
**Pull request by zfben**
Fix style when indexType is ol.
Display pure ol ui.

Before:

image

After:

image

### CODE REVIEW

**Review by Mister-Hope — CHANGES_REQUESTED** [review]
Before/After screenshot is required

**Comment by zfben** [comment]
> Before/After screenshot is required

@Mister-Hope I have updated the description

**Comment by Mister-Hope** [comment]
Actually I do not like the after outlook,  I hope you already know that the marker  could be customized through csc,  For the first level I would recommend Roman number,  That is I II III IV....,   And the second level can be arabic numbers,  The third level is the sixth can be Roman numbers in lowercase,  I think this kind of a look can be far more reasonable,  I test more better on a11y

**Comment by zfben** [comment]
> Actually I do not like the after outlook, I hope you already knew that the marker could be customized through css, For the first level I would recommend Roman number, That is I II III IV...., And the second level can be arabic numbers, The third level can be Roman numbers in lowercase, I think this kind of a look can be far more reasonable, also much better on a11y
> 
> Dropping the h3 tag has no advantage,

@Mister-Hope Actually pure ol is much easier to be customized through css.

There are 2 choosen for users:

1. default style and default index style.
2. pure ol style with or without customized css.

**Comment by zfben** [comment]
@Mister-Hope do you have new questions about this request?

**Comment by zfben** [comment]
@Mister-Hope it's so regrettable that you rudely closed the pull request without any words.

**Comment by Mister-Hope** [comment]
> Actually I do not like the after outlook,  I hope you already knew that the marker  could be customized through css,  For the first level I would recommend Roman number,  That is I II III IV....,   And the second level can be arabic numbers,  The third level can be Roman numbers in lowercase,  I think this kind of a look can be far more reasonable,  also much better on a11y 
> 
> Dropping the h3 tag has no advantage,

then what's this

**Pull request closed without merging**
