### PR TITLE
feat(comment): add utterances

### PR DESCRIPTION
**Pull request by Cokaps**
[Utterances comment system](https://github.com/utterance/utterances) have a lot of themes
First time I've contributed such big PR like this, so there may be some faults.
Some useful things found on the internet:  

* [A issue on utterances repo about Vue / Vuepress integration](https://github.com/utterance/utterances/issues/231)
* [vue-utterances](https://github.com/utterance/utterances/issues/231) only support vue3 so may be wait for vuepress@next

### CODE REVIEW

**Comment by Mister-Hope** [comment]
PR minimal requirements:

- workable
- not affecting current features

I don't think this pr is workable.

**Comment by Cokaps** [comment]
Let's me check again

**Comment by Mister-Hope** [comment]
The pr should be able to built.

**Comment by Cokaps** [comment]
Just have some question:
What should I import here? (the package of utterances which can be downloaded [here](https://utteranc.es/client.js)?)
image

**Comment by Mister-Hope** [comment]
Maybe you should try to remove the exsiting script tag and inject a new script tag with correct props every time a route is changed

**Comment by Mister-Hope** [comment]
For the options for plugin, you should write thte interface yourself.

**Comment by Mister-Hope** [comment]
I just read through utterances docs. If you really want to use it, I strongly recommend you to use it with `custom layout` provide by theme. Instead of budling it in to the comment plugins. In this case, you will need a component mounted to the pageBottom slot, and doing:

Temove the exsiting script tag and inject a new script tag with correct props every time a route is changed

**Comment by Mister-Hope** [comment]
BTW, a docs update about adding a guide on how to use utterances in theme is still wellcome👍

**Comment by Cokaps** [comment]
Is there any ways to detect dark/light mode change in vuepress-theme-hope (the Dark/Light mode button). Here is my code which using the id of the button:
```vue

<template>
  <div v-show="commentDisplay" class="utterances">
    <div id="comment" />
  </div>
</template>

<script>
export default loadUtterances = () => {
    typeof(element) != 'undefined' && element != null ? document.getElementById('utterances').remove : console.log("Init Utterances")
    let theme = document.getElementById("DarkLightModeChangeButton") === "dark" ? 'github-dark' : 'github-light';
    let utterances = document.createElement('script');
    utterances.src = 'https://utteranc.es/client.js';
    utterances.setAttribute('repo', '');
    utterances.setAttribute('issue-term', '');
    utterances.setAttribute('theme', theme);
    utterances.setAttribute('crossorigin', 'anonymous');
    utterances.setAttribute('id', 'utterances');
    document.getElementsByClassName('utterances').appendChild(utterances);
}
loadComment();
document.getElementById("DarkLightModeChangeButton").onclick = loadComment()
</script>
```

**Comment by Mister-Hope** [comment]
I will point out for you after I get home

**Comment by Mister-Hope** [comment]
This is what you should do:

https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/2b2e40eea9a920b88685edf2f9b7a0278e428c58/packages/md-enhance/src/client/Mermaid.ts#L116-L128

and don't forget to destory the watcher when unmounted:

https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/2b2e40eea9a920b88685edf2f9b7a0278e428c58/packages/md-enhance/src/client/Mermaid.ts#L133-L135

**Comment by Mister-Hope** [comment]
I just rethink about this feature, and it can be acceptale if the addtion lines are no more than 200. So wecome to finish this PR if you like.

**Comment by Cokaps** [comment]
> I just rethought about this feature, and it can be acceptale if the addtional lines are no more than 200. So wecome to finish this PR if you like.

I will try my best to finish this PR, may you re-open it?

**Comment by Mister-Hope** [comment]
I cannot reopen it(GitHub stops me because of unrelated history), so I suggested you to open a new one 😀

**Comment by Mister-Hope** [comment]
Any update about this?

**Comment by Cokaps** [comment]
I tried to fix the problem, but it doesn't help so I revert it (as you can see from the doc, it must be `issue-term` to make utterances work but if I use `issue-term`, syntax errors). Btw, why there are some conflicts here?

**Comment by Cokaps** [comment]
Sorry, I've tried my best. Really sory

**Pull request closed without merging**
