### PR TITLE
docs: clarify the default value of writing date

### PR DESCRIPTION
**Pull request by kaikaibenkai**

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Why to you think your changes are better?

**Comment by kaikaibenkai** [comment]
It explicitly states that `date` in the frontmatter will replace the one from Git. The original guidance could have been misinterpreted as:

> In Git-enabled projects, writing dates will be overwritten according to Git's history.

**Comment by Mister-Hope** [comment]
So what'sthe meaning fallback?

**Comment by kaikaibenkai** [comment]
> So what's the meaning of fallback?

If *?*, fallback to the first commit date of current file.

**Comment by kaikaibenkai** [comment]
I know my comprehension skills are a bit weak. Thank you for your time!

**Pull request closed without merging**
