### PR TITLE
fix(theme): fix footer layout, (fix #2687)

### LINKED ISSUE #2687: 加密时，渲染问题，本地调试出现bug[Bug]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

image

没有任何报错，输入密码后就正常了。

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yorunning**

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Footer could have more height than this, I am thinking adding a flex container outside, and let page to have flex-grow:1

**Comment by Mister-Hope** [comment]
Can you try to achieve that?

**Comment by yorunning** [comment]
I will just fix style errors

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/c05f11311153cf9d02927db228a0400ac2344b4f

**Pull request closed without merging**
