### PR TITLE
Update Translate

### PR DESCRIPTION
**Pull request by Hkr32**
Please check if I translated everything?

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Playground is missing, I think I left a comment for you at https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/1d7fa0d79e5454e85b0f2bd9d98760dd206f9cf0

**Comment by Mister-Hope** [comment]
I may update docs for theme about that function in a few days, I will tell you when I complete the job.

**Comment by Hkr32** [comment]
> Playground is missing, I think I left a comment for you at that issue with [1d7fa0d](https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/1d7fa0d79e5454e85b0f2bd9d98760dd206f9cf0)

To be honest, I didn’t understand what needs to be translated there, there is no translation there, I haven’t translated the demo yet, any plugins

**Comment by Mister-Hope** [comment]
Yes, I do realized that after comment. I should add that in theme docs

**Pull request merged**
