### PR TITLE
Update demo.md

### PR DESCRIPTION
**Pull request by xwzbupt**
add a new demo into set of examples.

### CODE REVIEW

**Review by Mister-Hope — CHANGES_REQUESTED** [review]
Can you learn some markdown basics and check the page carefully?

**Comment by xwzbupt** [comment]
> Can you learn some markdown basics and check the page carefully?

I know markdown very much, but I wonder whether my `URL` should be added to `## 更多`.

**Comment by Mister-Hope** [comment]
add one like line 126-129

**Comment by Mister-Hope** [comment]
Besides merging this, I would like to warn you some limitations.

All sites should be open source to be one the list, so that people can check them as an example (or reference)

However, you are using encryption feature, in this case the encryption may not be useful.

**Review by Mister-Hope — APPROVED** [review]

**Pull request merged**
