### PR TITLE
feat(theme): Add Finnish language support

### PR DESCRIPTION
**Pull request by korhox**
Hello!

This pull request adds 🇫🇮 Finnish language support to the theme.

### CODE REVIEW

**Comment by Mister-Hope** [comment]
hi, could you please uprade plugin locales as well?

**Comment by korhox** [comment]
Hi! I can update everything needed. Could you point me to the correct files?

**Comment by Mister-Hope** [comment]
I will simply the jobs, just wait a couple of minutes.

**Comment by Mister-Hope** [comment]
I tried to finish some locales by gh copilot to let you check it, but copilot service is not stable in China mainland and my network provider may ban this api periodly, so you may need to complete some of them yourself 
image

**Comment by Mister-Hope** [comment]
Instructions are at [here](https://theme-hope.vuejs.press/contribution.html), post if you meet any issues.

**Pull request merged**
