### PR TITLE
feat: Add ja support.

### PR DESCRIPTION
**Pull request by unknowIfGuestInDream**
I've added Japanese resource support, please review it.

In addition, I suggest changing "/jp/" to "/ja/" and "jp-JP" to "ja-JP".

Above.

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Thanks for catching this.

**Comment by unknowIfGuestInDream** [comment]
> > In addition, I suggest changing "/jp/" to "/ja/" and "jp-JP" to "ja-JP".
> 
> Welcome to change this in the same pr.



> > In addition, I suggest changing "/jp/" to "/ja/" and "jp-JP" to "ja-JP".
> 
> Welcome to change this in the same pr.

I have revised and submitted, please review it.

Above.

**Comment by unknowIfGuestInDream** [comment]
> Can you support other plugins as well? The theme is using other plugins in this repo, so a full support of japanese need to update all the locale.ts in this repo, e.g: https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/packages/comment2/src/node/locales.ts

OK, I will add to this.

Above.

**Comment by Mister-Hope** [comment]
All the locale related file should be named `locales.ts` or under `locales` folder under `src/node`

**Comment by unknowIfGuestInDream** [comment]
> All the locale related file should be named `locales.ts` or in `locales` folder under `src/node`

OK, thanks, I will add it as soon as possible.

Avove.

**Comment by unknowIfGuestInDream** [comment]
> Can you support other plugins as well? The theme is using other plugins in this repo, so a full support of japanese need to update all the locale.ts in this repo, e.g: https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/packages/comment2/src/node/locales.ts

I have improved the Japanese language resources, please review it.

Above.

**Review by Mister-Hope — APPROVED** [review]

**Pull request merged**
