### PR TITLE
 feat: add I18n support for french

### PR DESCRIPTION
**Pull request by celi28**
Hello,

This PR have for objective to add I18n support for French language.

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Could you please update all plug-ins as well?

**Comment by celi28** [comment]
@Mister-Hope Fixed linting on index.ts and updated package.json to latest.

**Comment by Mister-Hope** [comment]
> Could you please update all plug-ins as well?

What I am trying to request is to support locales in plug-ins, as theme is suing them, so you will need to update them if you need a full support for French

**Comment by celi28** [comment]
> Could you please update all plug-ins as well?

I believe it was you asked for.
Sorry, I will revert the push.

**Comment by celi28** [comment]
I do not found plugins internationalization configurations on https://vuepress-theme-hope.github.io/v2/config/i18n.html#setting-language

Can you please indicate me where are the related configs ?

**Comment by Mister-Hope** [comment]
image
image

**Comment by Mister-Hope** [comment]
E.g.: https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/packages/pwa2/src/node/locales.ts

**Comment by celi28** [comment]
Got it. Thanks for the explanations !

**Comment by Mister-Hope** [comment]
comment2 is missing

**Comment by celi28** [comment]
Added !

**Comment by Mister-Hope** [comment]
Thanks, we will delay new version release until we merged #1731. So you may need to wait for a few days.

**Review by Mister-Hope — APPROVED** [review]

**Pull request merged**
